### ISSUE TITLE
feature #1: user can search for an artist

### ISSUE THREAD

**Issue by bernardino8** [bernardino8/ajax-project#1]
## ⚙️ Feature

user can search for an artist

## 📐 Functionality

user will be able to interact with the search bar/button and the search/source navigation links

## 🖼️ Wireframes

![Screen Shot 2021-09-21 at 3 09 30 PM](https://user-images.githubusercontent.com/88168364/134254484-78720f7b-5421-4883-ab0d-be0035674341.png)
![Screen Shot 2021-09-21 at 3 15 02 PM](https://user-images.githubusercontent.com/88168364/134255017-ee4f868e-ca85-47b0-aea4-8a935a2afa88.png)

## ✅ Task List

- [x] create html layout
- [x] create stylesheet to style accordingly
- [x] create navigation header (title, links) and for potential interactivity 
- [x] add an input element of type search
- [x] create search button
- [x] add media queries for responsiveness
- [x] adjust styles continually 
- [x] add script for search functionality (account for spaces when searching via `pattern` attr, if necessary)
- [x] make sure that click targets are either `<a>` or `<button>` elements.
- [x] make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **clean up/refactor**
  - [x] remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] remove all console logs.
  - [x] remove all commented out code.
  - [x] remove all CSS properties that have no effect.
  - [x] check all code for proper formatting and indentation.
  - [x] confirm that there are no errors in the console while using the application.
  - [x] confirm that all previous functionality still works without errors.
  - [x] confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
