### ISSUE TITLE
feature #2: user can view the artist’s work/information

### ISSUE THREAD

**Issue by bernardino8** [bernardino8/ajax-project#2]
## ⚙️ Feature

user can view the artist’s work/information, i.e., if i search the artist "claude monet", i will receive all the artist's artwork with the respective information about each piece of artwork

## 📐 Functionality

user will be able to fully interact with the search functionality, being able to search for any artist and their respective artwork within the API directory

## 🖼️ Wireframes

![Screen Shot 2021-09-21 at 3 38 40 PM](https://user-images.githubusercontent.com/88168364/134256934-61b47c92-d6cc-46da-9974-6f5511344ffb.png)
![Screen Shot 2021-09-22 at 4 26 55 PM](https://user-images.githubusercontent.com/88168364/134434954-eefcdffe-d430-4596-9f82-dd6a0ac5cd91.png)
## ✅ Task List

- [x] create placeholder data (html); referencing wireframes
- [x] style placeholder data (css); referencing wireframes
- [x] create dom tree; reference placeholder data/styles
- [x] resolve issue where an object property and/or property key breaks loop that's iterating through each object due to the property and/or property key being undefined (only occurs in certain instances, i.e. for `object[i].people[i].displayname` or `object[i].people[i].name`)
- [x] modify dom tree to pull the correct data
- [x] delete placeholder data (html)
- [x] modify `GET` request to account for space when searching an artist name
- [x] adjust stylesheet, if necessary
- [x] use [google webfonts helper](https://github.com/majodev/google-webfonts-helper) to self-host fonts to lessen load weight
- [x] make sure that click targets are either `<a>` or `<button>` elements.
- [x] make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **clean up/refactor**
  - [x] remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] remove all console logs.
  - [x] remove all commented out code.
  - [x] remove all CSS properties that have no effect.
  - [x] check all code for proper formatting and indentation.
  - [x] confirm that there are no errors in the console while using the application.
  - [x] confirm that all previous functionality still works without errors.
  - [x] confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
